GET http://localhost:5000/api/user/eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2NDAwZDg2ZTI5MmIwNmZmNTFkNWM0YjQiLCJlbWFpbCI6InBvdHRlckBob2d3YXJ0cy5jb20iLCJpYXQiOjE2NzgyMDcyMjksImV4cCI6MTY3ODIxMDgyOX0.318VKBWnxLntUnHRdJslB9wFGfI5q0-Zz34_r_gdQtc HTTP/1.1