DELETE http://localhost:5000/api/tasks/640227c15afa256f6b85dad5 HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2NDAwZDg2ZTI5MmIwNmZmNTFkNWM0YjQiLCJlbWFpbCI6InBvdHRlckBob2d3YXJ0cy5jb20iLCJpYXQiOjE2Nzg0NzI3OTAsImV4cCI6MTY3ODQ3Mjg1MH0.SXEUYsPhcyG2dw3C5JYyw-Lc_C2y0diORYCwpZaOFyE