GET http://localhost:5000/api/tasks/ HTTP/1.
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2NDAwZDg2ZTI5MmIwNmZmNTFkNWM0YjQiLCJlbWFpbCI6InBvdHRlckBob2d3YXJ0cy5jb20iLCJpYXQiOjE2Nzg3ODkwODUsImV4cCI6MTY3ODc4OTE0NX0.armX9GM2t4aa5y77fHR8StTinf18ullAJ770JKjOH5Q